### ISSUE TITLE
Google Calendar API batch request (Event Insertion) - not all callbacks are called

### ISSUE THREAD

**Issue by dizpers** [googleapis/google-api-python-client#1026]
I have the code, which makes 50 Google Calendar API Calls in the batch (Event Insertion). Events are created successfully and I want to make a record in the database. To make it I assign a callback for each insertion. Unfortunately only limited (and random) number of callbacks are called. In the meantime I tried `httplib2.debuglevel = 4` and had seen that API response includes a response per each Insertion (request).

So it sounds like a bug. Each callback must be called.

#### Environment details

  - OS type and version: Ubuntu 18.04.2
  - Python version: 3.7.4
  - pip version: 19.2.2
  - `google-api-python-client` version: 1.10.0

#### Steps to reproduce

  1. Create a batch request with 50 Google Calendar Event Insertion tasks
  2. See that only some random number of callbacks would be called

#### Code example

```python
batch = service.new_batch_http_request()

for event, account_id in events_and_accounts:
    batch.add(
        service.events().insert(
            body=event,
            calendarId='primary'
        ),
        callback=partial(callback, account_id)
    )

batch.execute()
```

#### Stack trace

No stack trace.

**Comment by busunkim96** [comment]
Hi @dizpers,

Thank you for filing an issue. Do you have any more information on which callbacks are called vs. not called? Are all the individual requests succeeding?

The expected behavior is for the callback to be called on every response (see code below):

https://github.com/googleapis/google-api-python-client/blob/f3348f98bf91a88a28bf61b12b95e391cc3be1ff/googleapiclient/http.py#L1550-L1568

**Comment by parthea** [comment]
Hi @dizpers,

I'm going to close off this issue due to inactivity. If you're still having trouble, please re-open it with more information.
