### ISSUE TITLE
discovery document caching is broken in default installation

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/google-api-python-client#1061]
`google-api-python-client` has an integrated caching system for discovery documents, but it isn't enabled in the default installation [1].  The cache depends on the `LockedFile` implementation from `oauth2client<4.0.0`.  If I manually install `oauth2client==3.0.0`, the cache is activated.  This makes issue #1056 much less painful.

Ideally, the cache implementation should be fixed so it works without installing old versions of `oauth2client`.

[1] - https://github.com/googleapis/google-api-python-client/blob/30eff9d8276919b8c4e50df2d3b1982594423692/googleapiclient/discovery_cache/file_cache.py#L32

**Comment by busunkim96** [comment]
Hi,

The current cache implementation depends on oauth2client, which is the deprecated auth client (it hasn't been released since September 2018).

We'll be downloading discovery docs and distributing them with the library itself sometime this quarter. At that point the caching should be unnecessary.

**Comment by parthea** [comment]
Hi @rvandegrift, 

I'm going to close this issue as we are shipping discovery documents with the library moving forward. This is being tracked in #1063. PR #1109 is almost complete and I expect it will be merged in 2021 Q1.
