### ISSUE TITLE
Specify latest version that works with Python 2.7

### ISSUE THREAD

**Issue by pb-jeff-oneill** [googleapis/google-api-python-client#1150]
PyPI and other Google Cloud documentation ([example](https://cloud.google.com/compute/docs/tutorials/python-guide)) state that `google-api-python-client` supports Python 2.7.

This Github page states that <3.6 is not supported.  

I realize you likely can't get these other Google pages updated, but could you at least state the latest version of `google-api-python-client` that works with Python 2.7?

Us poor developers who still have to deal with Python 2.7 would greatly appreciate it!

**Comment by parthea** [comment]
Hi @pb-jeff-oneill,

Python 2.7 was only removed from master in a recent PR (#961). We haven't published a release since the PR was merged so the current release v1.12.8 is likely working with python 2.7. Any time there is going to be a breaking change, we increment the major version of the release so the next release where python 2.7 is removed will be 2.0.0. I'd recommend that you use `google-api-python-client<2.0` if you are still working with python 2.7.

 I'm going to close this off but please re-open if you require additional information.
