### ISSUE TITLE
Access all calendar in a much more concise way

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1153]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
as you can see in the [github issue](https://github.com/googleapis/google-api-python-client/issues/1152), I had to make a super nested loop to just find the current event of the user. Not only this made the end result not work all the time but heavily prone to a break due to the heavily nested structure.
 **Describe the solution you'd like**
events_result = service.events().list(calendarId= **"Al"l** , timeMin=now,
                                        maxResults=10, singleEvents=True,
                                        orderBy='startTime').execute()
could replace something like All to be able to retrieve all of the users calendar instead of just one.
 **Describe alternatives you've considered**
It would be great if we can also have a feature where with one if not a few lines we can know the google event of the user at the point in time.
 **Additional context**

**Comment by parthea** [comment]
Unfortunately, this feature request is out of the scope of this library as it is related to the underlying API and not the `google-api-python-client` library itself. Please follow the steps outlined on the [Google Calendar API Help Site](https://developers.google.com/calendar/support) if you'd like to submit a feature request to show events from all calendars in a single call to service.events().list(). Follow the steps under the [missing features](https://developers.google.com/calendar/support#missing_features) section. Once you create the feature request, please add the link here so that others can 'star' it which may raise visibility of the feature request.

**Comment by parthea** [comment]
I've closed this issue but please feel free to re-open with more information if you have additional questions.
