### ISSUE TITLE
becasue of google-api-python-client==1.6.2 our python service build is failing

### ISSUE THREAD

**Issue by nilesh-pawar-by** [googleapis/google-api-python-client#1204]
we are using google-api-python-client==1.6.2 in our python service and its not supporting python 2.7 anymore but our service is using pyhton 2.7 so we are getting build issue while  Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.2->JDAMicroserviceDoitPlugin==10.1.0)
Using cached https://jdasoftware.jfrog.io/jdasoftware/api/pypi/pypi/packages/packages/2d/d3/41b3db87f262debadb153900d4e6f8d61aa87187dd6fedd855ed24e8526d/rsa-4.7.1.tar.gz
rsa requires Python '>=3.5, <4' but the running Python is 2.7.13.

**Comment by parthea** [comment]
Hi @nilesh-pawar-by,

Although python 2.7 is not supported in the master branch, we have not released a new version of `google-api-python-client` yet which drops support for Python 2.7. The last release ([1.12.8](https://github.com/googleapis/google-api-python-client/releases/tag/v1.12.8)) still supports python 2.7. Based on [this](https://stuvel.eu/post/2020-06-18-python-rsa-4-6-released/) blog post, it appears that the last version of `rsa` which supports python 2.7 is version 4.6. Try pinning `rsa` to version 4.6 as a workaround.

**Comment by parthea** [comment]
I'm going to close off this issue, but if I've missed something please feel free to re-open it with more information.

**Comment by parthea** [comment]
Hi @nilesh-pawar-by,

I just wanted to follow up and mention it is recommended that you use [google-auth](https://github.com/googleapis/google-auth-library-python) instead of [oauth2client](https://github.com/googleapis/oauth2client).  `oauth2client` is archived and the repo is marked as read-only. You'll run in to fewer issues using `google-auth` which is actively supported and has the correct pin to `rsa` version 4.6 [here](https://github.com/googleapis/google-auth-library-python/blob/master/setup.py#L26).

**Comment by nilesh-pawar-by** [comment]
Hi parthea with rsa 4.6 issue is resolved

**Comment by parthea** [comment]
This has been resolved in the v1 branch (09155f1). If anyone runs into this, please consider these other recommended steps:

1) If you can upgrade to python 3.x, please do so as we have dropped support in master. The [v1 branch](https://github.com/googleapis/google-api-python-client/tree/v1) is the branch where we still support python 2.

2) If you cannot upgrade to python 3.x and you are using `oauth2client`, please consider using `google-auth` instead. `oauth2client` is archived and the repo is marked as read-only so we are unable to support `oauth2client` in terms of bug fixes. 

3) If you cannot move away from `oauth2client`, you should pin to `rsa` version 4.5 in order to continue to have python 2 support as this is the last version of `rsa` that supports python 2.
