### ISSUE TITLE
UnknownApiNameOrVersion exception with commentanalyzer

### ISSUE THREAD

**Issue by enkeyz** [googleapis/google-api-python-client#1238]
#### Environment details

  - OS type and version: latest Manjaro Linux
  - Python version: 3.9.1
  - pip version: 20.3.1
  - `google-api-python-client` version: 2.0.2

#### Steps to reproduce
Just got my API access from them, made a project, added an API key, and their sample code wouldn't work.

  1. Run code - it's from the offical website https://support.perspectiveapi.com/s/docs-sample-requests

#### Code example

```python
from googleapiclient import discovery
import json

API_KEY = ""

# Generates API client object dynamically based on service name and version.
service = discovery.build("commentanalyzer", "v1alpha1", developerKey=API_KEY)

analyze_request = {
    "comment": {"text": "friendly greetings from python"},
    "requestedAttributes": {"TOXICITY": {}},
}

response = service.comments().analyze(body=analyze_request).execute()


print(json.dumps(response, indent=2))
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/enkeyz/stuff/discord/detox.ai/bot/test.py", line 7, in <module>
    service = discovery.build("commentanalyzer", "v1alpha1", developerKey=API_KEY)
  File "/home/enkeyz/.local/share/virtualenvs/detox.ai-WfgfN2Jd/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/enkeyz/.local/share/virtualenvs/detox.ai-WfgfN2Jd/lib/python3.9/site-packages/googleapiclient/discovery.py", line 273, in build
    content = _retrieve_discovery_doc(
  File "/home/enkeyz/.local/share/virtualenvs/detox.ai-WfgfN2Jd/lib/python3.9/site-packages/googleapiclient/discovery.py", line 387, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: commentanalyzer  version: v1alpha1

```

**Comment by jdelalande** [comment]
Hello,

I am having the same issue on mybusiness v4 since march 4th. 
Connection was allrigth until then (using this connection for several months).

`print(creds.valid)
import sys
print(sys.version)
#print (googleapiclient.__version__)
SCOPES = ['https://www.googleapis.com/auth/business.manage']
discovery_uri = "https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p5.json"
service = build('mybusiness', 'v4', credentials=creds, discoveryServiceUrl = discovery_uri)`

`
True
3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
UnknownApiNameOrVersion                   Traceback (most recent call last)
<command-3982221443965922> in <module>
      5 SCOPES = ['https://www.googleapis.com/auth/business.manage']
      6 discovery_uri = "https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p5.json"
----> 7 service = build('mybusiness', 'v4', credentials=creds, discoveryServiceUrl = discovery_uri)

/databricks/python/lib/python3.7/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

/databricks/python/lib/python3.7/site-packages/googleapiclient/discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery)
    280                 developerKey,
    281                 num_retries=num_retries,
--> 282                 static_discovery=static_discovery,
    283             )
    284             service = build_from_document(

/databricks/python/lib/python3.7/site-packages/googleapiclient/discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, serviceName, version, cache, developerKey, num_retries, static_discovery)
    385             return content
    386         else:
--> 387             raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
    388 
    389     actual_url = url

UnknownApiNameOrVersion: name: mybusiness  version: v4`

**Comment by oliverkostoff** [comment]
I had something very similar on Python 3.8.8 ( from this image https://hub.docker.com/_/python, tag: 3.8 ) from GCP CloudRun container:

`Traceback (most recent call last): File "/usr/local/bin/bottle.py", line 868, in _handle return route.call(**args) File "/usr/local/bin/bottle.py", line 1748, in wrapper rv = callback(*a, **ka) File "/srv/main.py", line 187, in inventory gcp_client = GCPClient(project=PROJECT, region=REGION) File "/srv/main.py", line 46, in __init__ self.compute = googleapiclient.discovery.build('compute', 'v1') File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper return wrapped(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 273, in build content = _retrieve_discovery_doc( File "/usr/local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 387, in _retrieve_discovery_doc raise UnknownApiNameOrVersion("name: %s version: %s" % (serviceName, version)) googleapiclient.errors.UnknownApiNameOrVersion: name: compute version: v1`

This worked flawlessly till Thu last week. I now tested with newer image ( Python:3.9.2 ) and the error is gone. Please document any interpreter requirements, if any.

**Comment by enkeyz** [comment]
My problem is that my discord bot needs this API to work. Development standing still until this issue resolved.

**Comment by busunkim96** [comment]
Hi folks,

Please see https://github.com/googleapis/google-api-python-client/issues/1225.

**Comment by enkeyz** [comment]
Sorry, but that doesn't solve any issue I have. How can I get the discovery url? That issue you linked doesn't really help at all.

**Comment by busunkim96** [comment]
Hi @enkeyz,

From looking at the NodeJS sample linked on the [documentation page](https://support.perspectiveapi.com/s/docs-sample-requests), it looks like 'https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1' is the discovery URL.

```py
from googleapiclient import discovery

client = discovery.build(
    "commentanalyzer",
    "v1alpha1",
    discoveryServiceUrl="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
    static_discovery=False,
)

```

I'll reach out to the comment analyzer team to see if they can get their API listed in the directory.

**Comment by busunkim96** [comment]
Filed 82170350 internally to ask the API owners to update the sample or list the API in the directory.
