### ISSUE TITLE
httplib2.RedirectMissingLocation error when creating doubleclickbidmanager query

### ISSUE THREAD

**Issue by andrewkisel** [googleapis/google-api-python-client#1253]
Looks like the HTTP response code API is returning is 303, so the issue doesn't seem to be related to other RedirectMissingLocation issues w/code 308. Still, I tried both downgrading httplib2 from 0.19.0 to 0.15.0 and upgrading google-api-python-client from 1.12.8 to 2.0.2 but neither helped.

#### Environment details

  - CentOS 7
  - Python version: Python 3.7.4
  - pip version: pip 21.0.1
  - `google-api-python-client` version: 1.12.8 (same in 2.0.2)

#### Steps to reproduce

  1. Create a doubleclick bid manager client using googleapiclient.discovery.build()
  2. Create any query using dbm_client.queries().createquery().execute()

#### Code example

```
dbm_client = build('doubleclickbidmanager', 'v1.1',
                   credentials=creds, cache_discovery=False,
                   num_retries=6)
query_config = {
            'kind': 'doubleclickbidmanager#query',
            'metadata': {
                'title': 'test',
                'dataRange': 'CUSTOM_DATES',
                'format': 'CSV'
            },
            'params': {
                'metrics': ['METRIC_IMPRESSIONS', 'METRIC_CLICKS',
                            'METRIC_TOTAL_MEDIA_COST_USD',
                            'METRIC_LAST_CLICKS',
                            'METRIC_LAST_IMPRESSIONS',
                            'METRIC_RICH_MEDIA_VIDEO_FIRST_QUARTILE_COMPLETES',
                            'METRIC_RICH_MEDIA_VIDEO_MIDPOINTS',
                            'METRIC_RICH_MEDIA_VIDEO_THIRD_QUARTILE_COMPLETES',
                            'METRIC_RICH_MEDIA_VIDEO_COMPLETIONS',
                            'METRIC_RICH_MEDIA_VIDEO_PLAYS'],
                'type': 'TYPE_GENERAL',
                'filters': [
                    {
                        'type': 'FILTER_ADVERTISER',
                        'value': account
                    }
                ],
                'groupBys': ['FILTER_INSERTION_ORDER', 'FILTER_DATE']
            },
            'schedule': {
                'frequency': 'ONE_TIME'
            },
            'reportDataStartTimeMs': since,
            'reportDataEndTimeMs': through,
        }
        query_id = dbm_client.queries().createquery(
            body=query_config).execute()['queryId']
```

#### Stack trace

```
  File "env/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "env/lib/python3.7/site-packages/googleapiclient/http.py", line 909, in execute
    headers=self.headers,
  File "env/lib/python3.7/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "env/lib/python3.7/site-packages/google_auth_httplib2.py", line 201, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "env/lib/python3.7/site-packages/httplib2/__init__.py", line 1709, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "env/lib/python3.7/site-packages/httplib2/__init__.py", line 1448, in _request
    _("Redirected but the response is missing a Location: header."), response, content,
httplib2.error.RedirectMissingLocation: Redirected but the response is missing a Location: header.
```

**Comment by parthea** [comment]
Hi @andrewkisel,

Thanks for the detailed information. My initial thought is that there is a legitimate error that is being returned from the `doubleclickbidmanager` API which has HTTP error code 303 as defined [here](https://developers.google.com/bid-manager/core_errors#SEE_OTHER). For HTTP error code 303, the description is `Your request was processed successfully. To obtain your response, send a GET request to the URL specified in the Location header.` There is an issue that the location header is missing in the HTTP response so `httplib` cannot complete the redirect so you get `httplib2.error.RedirectMissingLocation` instead of a helpful error message. I believe this is a bug with the `doubleclickbidmanager` API as the [documentation](https://developers.google.com/bid-manager/core_errors#SEE_OTHER) states that a `location` header will be included with HTTP error 303. To confirm, you could try out a similar request in the 'Try this API' interface on [this page](https://developers.google.com/bid-manager/v1.1/queries/createquery) and I would expect the location header is not present in the response with HTTP error 303. 

Please fill out this [support form](https://support.google.com/displayvideo/contact/nghelp_contact_form) which is on [this](https://developers.google.com/bid-manager/get-support) support page to get help from the specialized team for the  `doubleclickbidmanager` API.

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

I've also updated an internal ticket to increase visibility of this issue. Googlers see b/165005527. I'm going to close off the issue since it is an issue with the API rather than the python client library in this Github repo.

**Comment by andrewkisel** [comment]
@parthea Thank you! I figured it was something with the API itself and submitted a ticket using the support form right away, just wanted to see if someone has more wisdom on this 😄
