### ISSUE TITLE
Google Push Notification: 'reason' : 'notFound'

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1327]
#### Environment details

  - OS type and version:
  - Python version: `python --3.8.5`
  - pip version: `pip --21.0`
  - `google-api-python-client` version: `2.1.0`

#### Steps to reproduce

  1. registered domain and verified it as the [doc](https://developers.google.com/calendar/v3/push#registering-your-domain) requested 

#### Code example

```
@blueprint.route("/notifications", methods={'GET','POST'})
def timeBlocker():
    email = request.json.get('email')
    user = User.query.filter_by(email=email).first()
    acessToken = accessToken(email, user.refresh)
    body = {
        'id': '01234567-89ab-cdef-0123456789ab', 
        'type': 'web_hook',
        'address': 'https://<registeredDomain>/notifications'
    }
    headers = {'Authorization': 'Bearer ' + acessToken,
            'Content-Type': 'application/json'
            }
    calendarID = '...@group.calendar.google.com'
    req = requests.post(url=f'https://www.googleapis.com/calendar/v3/calendars/{calendarID}@group.calendar.google.com/events/watch', data = json.dumps(body), headers=headers) 
    return str(req.json())

```

#### Stack trace
```
{'error': {'errors': [{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}], 'code': 404, 'message': 'Not Found'}}

```
### Note:
The [doc](https://developers.google.com/calendar/v3/push#example) gives such code as an example:

```
POST https://www.googleapis.com/calendar/v3/calendars/my_calendar@gmail.com/events/watch
Authorization: Bearer auth_token_for_current_user
Content-Type: application/json

```
with my_calendar@gmail.com taken a calendarID when in reality the calendarIDs I've been receiving all end with @group.calendar.google.com. Thus, I am not sure if this is causing the case but keen to know how I shall fix the error.

Thanks!

**Comment by parthea** [comment]
Hi @DaniyalDhz 
 
Based on the sample code, it looks like you're calling the REST api directly using the `requests` library rather than `google-api-python-client`. The issue seems to be specific to the Calendar API rather than this library. The folks who maintain this issue tracker don't have expertise with any particular API. When the questions are more about the API than the library, we'll redirect you to the API support channel so you can get better quality answers. For the Calendar API please see https://developers.google.com/calendar/support.
