### ISSUE TITLE
UnknownApiNameOrVersion: name: youtube version: v3  reask....

### ISSUE THREAD

**Issue by passgall** [googleapis/google-api-python-client#1350]
#### Environment details

  - OS type and version:Win7 X64
  - Python version: `python 3.6.4
  - pip version: `pip 9.0.1
  - `google-api-python-client` version: 2.3.0

#### Steps to reproduce

  1. ?I have met this issue for stranging.I used this in vscode, It works well when excute with command line or terminal.But I want to package this code in exe file. It won't work!!
  2. ?I used proxy in my code and I have test with other website with no problem.

#### Code example
   socks.set_default_proxy(socks.SOCKS5, "xx.x.x.x", xxxx)
   socket.socket = socks.socksocket
   youtube_api = build('youtube', 'v3', developerKey = 'XXXXXXXXXXXXXXX')

**Comment by parthea** [comment]
Hi @passgall ,

Unfortunately I'm not able to re-produce the issue. My initial thought is that this could be related to issue #1275 but I don't have enough information to re-create the issue.  Please can you share additional information on how you're packaging the python code in your exe file?

In the meantime, you can set the `static_discovery` argument of `discovery.build()` to `False` to fetch discovery artifacts from the internet rather than the library. For reliability reasons, the default behavior is to fetch discovery artifacts from the library.

Change 

`youtube_api = build('youtube', 'v3', developerKey = 'XXXXXXXXXXXXXXX')` 

to 

`youtube_api = build('youtube', 'v3', developerKey = 'XXXXXXXXXXXXXXX', static_discovery=False)`

**Comment by parthea** [comment]
I'm going to close off this issue but please re-open it once you have more information.
