### ISSUE TITLE
Internal error when creating Filestore Instance

### ISSUE THREAD

**Issue by dfellmeth-google** [googleapis/google-api-python-client#1371]
I am attempting to use the filestore REST API to create a filestore instance, but what I would use as a set of parameters for a similar gcloud command yields a 500 Internal error response from the API with no additional details. How can I debug this error further?

```
filestore_client = discovery.build('file', 'v1', cache_discovery=False)
filestore_client.projects().locations().instances().create(
        parent='projects/%s/locations/%s' % (project, zone),
        instanceId=instance_name,
        body={
            'fileShares': [{
                'capacityGb': capacity,
                'name': share_name
            }],
            'networks': [{
                'network': network_name
            }]
        }
        ).execute()
```

This is the response I get (censored): 

```
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://file.googleapis.com/v1/projects/<project>/locations/<zone>/instances?instanceId=df-test&alt=json returned "An internal error has occurred (22434a96-375e-4498-916f-da3bbf2f4fed)">
```

**Comment by parthea** [comment]
Hi @dfellmeth-google,

I was able to reproduce the problem using the 'Try this API' interface on [this page](https://cloud.google.com/filestore/docs/reference/rest/v1/projects.locations.instances/create). The issue was resolved once I added `"tier": "STANDARD"` to the [request body](https://cloud.google.com/filestore/docs/reference/rest/v1/projects.locations.instances/create#request-body).

For example, I received HTTP Error Code 500 for the following request body:
```
{
  "fileShares": [
    {
      "capacityGb": 1024,
      "name": "share_name_1"
    }
  ],
  "networks": [
    {
      "network": "default"
    }
  ],
}
```

I received HTTP Error Code 200 for this request body with the `tier` field added in the request body:
```
{
  "fileShares": [
    {
      "capacityGb": 1024,
      "name": "share_name_1"
    }
  ],
  "networks": [
    {
      "network": "default"
    }
  ],
  "tier": "STANDARD"
}
```

**Comment by parthea** [comment]
Hi @dfellmeth-google,

I'm going to close this issue as it is a bug with the API rather than the python client library. Googlers see b/188979560 for internal bug to improve error message and documentation. Please re-open this issue if you have additional questions.
