### ISSUE TITLE
Adding Google Analytics WebProperties parameters

### ISSUE THREAD

**Issue by tonyrb** [googleapis/google-api-python-client#1458]
**Is your feature request related to a problem? Please describe.**

Not currently a problem, but I am seing missing parameter that look not possible to update when setting-up a properties.
search term exclusion
internal website exclusion
&
Search organic source parameter to add additional Search website.

 **Describe the solution you'd like**
Adding a API point to be able to create additional search term exclusion, internal website exclusion & search organic website using the API.

 **Describe alternatives you've considered**
Manually spend my time to update those values.

Thanks

**Comment by tonyrb** [comment]
Forgot to add for clarity this is for Google Analytics Management API.

https://developers.google.com/analytics/devguides/config/mgmt/v3

**Comment by parthea** [comment]
Hi @tonyrb,

Please submit feature requests and bug reports on the Google Analytics issue tracker [here](https://issuetracker.google.com/issues?q=componentid:187400) to log this feature request directly with the API team. Also see the [Google Analytics help page](https://developers.google.com/analytics/devguides/config/mgmt/v3/help). I'm going to close this issue as this is a feature request with the API rather than `google-api-python-client`, but please feel free to re-open this issue if you have additional questions.
