### ISSUE TITLE
Question: Google Analytics API quotas explanation

### ISSUE THREAD

**Issue by tonyrb** [googleapis/google-api-python-client#1459]
Hello,

I am trying to understand the quotas limits as available here https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas

And specifically here:
```
Write APIs
These quotas apply to the write (insert, update, patch, and delete) requests:

50 write requests per project per day, which can be increased
```

I am on a project where I am going to harmonize and create about 200 properties between two 360 account.

Goals is to harmonize the ecosystem of the company and provide same custom dimensions for each by keeping the previous one alive as well (we decided to start from 100, we are under GA360 licence term).
From my understanding I will need to create for many properties about 80 custom dimensions for each property to get to the 100 numbers...

With the current limits of 50 (and I have read after requests it's possible to get 500 top).
It will take me still ages to create a new property (or update one), add the missing property to reach 100 number and the associated views with the API.

Quick calculations assuming I have about 20 custom dim already created and got the upper limits of 500 (or maybe i might have more?)
- 80 custom dim to be created to get to 100 numbers
- 1 property update
- 1 view update
total per website 82 meaning per day I will be able to only create 6 property.

Is there a way to batch event and make it count like 1  api call (for the custom property creation)?

In addition is the API limits is setup per Accounts (we have about 2 Google 360 account) or it's separated for each account ?  (so I might divide by two the total estimated time to completion)

Thanks for the details provided

**Comment by parthea** [comment]
Hi @tonyrb,

Please follow the steps [here](https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas#additional_quota) to request a quota increase. As this question is specific to the Google Analytics API rather than `google-api-python-client`, I need to direct you to the [Google Analytics help page](https://developers.google.com/analytics/devguides/config/mgmt/v3/help) which will put in you contact with the API team. I don't want to give you any incorrect information, so it's better to use the links on the help page for API specific questions.

I'm going to close this issue but please feel free to re-open this issue if you have additional questions.

**Comment by tonyrb** [comment]
Thanks @parthea I now understand the difference and will pay attention more to redirect my questions to the right service ;).
I have manage to ask for the features as well (on the other tickers).
Sorry for the trouble and thanks for the help !
