### ISSUE TITLE
Interacting with Cloud Monitoring API V3 - Got an unexpected keyword argument "interval"

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [googleapis/google-api-python-client#1537]
We are trying to call this method: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list through python client and got execution complaining 'Got an unexpected keyword argument "interval"'

Below is the sample code

```
from googleapiclient import discovery
import datetime
from datetime import timedelta

monitor_client = discovery.build('monitoring', 'v3', cache_discovery=False)
service_list_parent = "projects/123456"
montioring_filter = """
metric.type="serviceruntime.googleapis.com/quota/allocation/usage" resource.type="consumer_quota"
"""
now = datetime.datetime.now(datetime.timezone.utc)
one_hour_ago = now - timedelta(hours=1)
now = now.isoformat()
one_hour_ago = one_hour_ago.isoformat()
interval = {
     "endTime": now,
     "startTime": one_hour_ago
}

metric = monitor_client.projects().timeSeries().list(name=service_list_parent, filter=montioring_filter, interval=interval).execute()

```

**Comment by busunkim96** [comment]
Hi,

If possible, please use `google-cloud-monitoring` as that client is more modern and should generally be easier to use. Differences between google-cloud-* clients and this library are described in https://github.com/googleapis/google-api-python-client#other-google-api-libraries. You can also find code samples for google-cloud-monitoring at  https://cloud.google.com/monitoring/docs/samples.

It looks like `list` expects separate args `interval_endTime` and `interval_startTime` rather than one `interval`.

https://googleapis.github.io/google-api-python-client/docs/dyn/monitoring_v3.projects.timeSeries.html#list

If you need to look up other methods the directory for generated reference documents is at https://googleapis.github.io/google-api-python-client/docs/dyn/.

**Comment by CharmanderJieniJieni** [comment]
Thanks @busunkim96 , `interval_endTime` worked for me! I think it is just the official api documentation a bit misleading because it is requesting a 'interval' object.
