### ISSUE TITLE
Can a service_account.Credentials instance be created from application default credentials instead of JSON file?

### ISSUE THREAD

**Issue by Rossco8** [googleapis/google-api-python-client#1591]
I need to be able to call the GMail API, which I can do locally on my laptop
```
credentials = service_account.Credentials.from_service_account_file(
                SERVICE_ACCOUNT_FILE, scopes=SCOPES)
delegated_credentials = credentials.with_subject(MAILBOX)
service = build('gmail', 'v1', credentials=delegated_credentials)
```
But I don't want to store the JSON key file when using Cloud Run. Is it possible to use the default credentials somehow? My Cloud Run instance is running as a service account with domain-wide delegation
```
def_creds, __ = google.auth.default(
            scopes=SCOPES
        )
auth_req = google.auth.transport.requests.Request()
def_creds.refresh(auth_req)
```
How can I use the `def_creds` to create a `service_account.Credentials` instance using the current service account?

**Comment by busunkim96** [comment]
Hi @Rossco8,

Thanks for opening a question. The default service account in the Cloud Run environment will be detected as [`google.auth.compute_engine.Credentials`](https://googleapis.dev/python/google-auth/2.3.3/reference/google.auth.compute_engine.html#module-google.auth.compute_engine) and there is no easy way to convert that to a service account.

Normally this does not matter, as the service account or compute engine credential will both have a valid token and are interchangeable for requests.

However, in your case it looks like you need to modify (1) the scopes and (2) the email to successfully do domain-wide delegation per https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority. The `scopes` are modifiable through the `scopes` kwarg, but I don't see a way to modify the `subject`.

[Impersonated credentials](https://googleapis.dev/python/google-auth/latest/reference/google.auth.impersonated_credentials.html#module-google.auth.impersonated_credentials) might work here, but I haven't tried it myself.


@arithmetic1728 Do you know of a clean way to do this? 

I found some similar questions but some are a bit old and I did not see a clear consensus on the best approach:

- https://stackoverflow.com/questions/59601045/gcp-cloud-function-domain-wide-delegation-using-application-default-credential
- https://stackoverflow.com/questions/53202767/gae-attributeerror-credentials-object-has-no-attribute-with-subject/57092533#57092533
- https://stackoverflow.com/questions/64658391/how-can-i-grant-a-cloud-run-service-access-to-service-accounts-credentials-with

**Comment by Rossco8** [comment]
Thanks for the info. I had a look at the impersonated credentials API and it doesn't appear to offer a way to create an instance of type `google.auth.service_account.Credentials` which (I think) is what I need

**Comment by arithmetic1728** [comment]
I don't know other ways to do so. We can use user credentials to impersonate service account credentials, but I don't know if it will work with domain wide delegation (because no where to specify the `sub` claim as Bu Sun mentioned). Impersonation doesn't create a service account credentials, it works the following way:

(1) configure the user/service account credentials for impersonation 
(2) create a token using the user credential
(3) call impersonation API with the token to exchange a new token
(4) this new token can be used as if it is generated by the service account

All details can be found here: https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#requesting_short-lived_credentials

The following is a curl example from the reference (here `gcloud auth application-default print-access-token` prints out the user credential token)
```
curl -X POST \
-H "Authorization: Bearer "$(gcloud auth application-default print-access-token) \
-H "Content-Type: application/json; charset=utf-8" \
-d @request.json \
"https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/SA_NAME@PROJECT_ID.iam.gserviceaccount.com:generateAccessToken"
```

**Comment by Rossco8** [comment]
Thanks. I've been able to avoid storing service account key files anywhere until this requirement came up. This will be the exception I suppose.
Happy to close this issue
