### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by GeorgeLubaretsi** [googleapis/google-api-python-client#166]
Is there django 1.9 support planned?

Also, 1.9 has introduced JSONField which could be used as credentials storage

**Comment by Alex3917** [comment]
Using JSONField is option. Another is converting them to JSON and storing them as a textfield. The advantage of this is that it's easy to encrypt the entire token before storing. (And there isn't really any benefit of storing the token as JSON, since you're usually going to need the entire token rather than just one field.)

`
class CredentialsField(models.Field, metaclass=models.SubfieldBase):
    def __init__(self, *args, **kwargs):
        if 'null' not in kwargs:
            kwargs['null'] = True
        super(CredentialsField, self).__init__(*args, **kwargs)

    def get_internal_type(self):
        return "TextField"

    def to_python(self, value):
        if value is None:
            return None

        if isinstance(value, oauth2client.client.Credentials):
            return value

        return value

    def get_prep_value(self, credential_object):
        if credential_object is None:
            return None

        return credential_object.to_json()
`

**Comment by busunkim96** [comment]
I'm opting to close this as it's unlikely we will implement it in the future.

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.
