### ISSUE TITLE
Sample file for GoogleDocs API still uses deprecated oauth2client module

### ISSUE THREAD

**Issue by jesuisme** [googleapis/google-api-python-client#1740]
Raising this issue per the instructions at https://google-auth.readthedocs.io/en/master/oauth2client-deprecation.html : 

Please update the GoogleDocs API v1 Python sample for extracting text from a document:
https://developers.google.com/docs/api/samples/extract-text?authuser=1

It still uses the deprecated oauth2client module rather than google-auth

Python: 3.8.3
OS: Windows 11

**Comment by busunkim96** [comment]
Hi @jesuisme,

Thanks for taking the time to file an issue. Unfortunately our team doesn't directly author all the samples that use google-api-python-client. It looks like the [Google Docs API Python quickstart](https://developers.google.com/docs/api/quickstart/python#step_2_configure_the_sample) uses google-auth instead of oauth2client. The credential fetching steps should be a drop in replacement for the sample you linked to.

If you encounter samples that have issues, the best way to file issues is to click on the "Send Feedback" button:

![image](https://user-images.githubusercontent.com/8822365/161088476-7a4ac121-22b0-480a-86ef-b14f98883d84.png)
