### ISSUE TITLE
Missing VPC Access Discovery Artifacts

### ISSUE THREAD

**Issue by qua-jones** [googleapis/google-api-python-client#1913]
vpc access artifacts currently missing in discovery cache
- https://vpcaccess.googleapis.com/$discovery/rest?version=v1
- https://vpcaccess.googleapis.com/$discovery/rest?version=v1beta1

**Comment by parthea** [comment]
We recommend using the VPC Access Cloud Client library located [here](https://github.com/googleapis/python-vpc-access) for the reasons mentioned [here](https://github.com/googleapis/python-vpc-access). 

If you'd still prefer to use Google API Client instead of the Cloud Client Library Client, please reply on this ticket and I can open a bug with the API team to request that the API be added to the public directory [here](https://www.googleapis.com/discovery/v1/apis).

Currently this library only fetches discovery documents from [this directory](https://github.com/googleapis/google-api-python-client/tree/main/googleapiclient/discovery_cache/documents). It contains all the discovery documents listed in the public directory here https://www.googleapis.com/discovery/v1/apis. Once a new API is added to the public directory, a PR will be opened automatically in this repo to add the new discovery artifacts.

**Comment by qua-jones** [comment]
It would be great if the VPC Access API could be added to the Google API Client. This would aid in limiting the amount of dependencies that would be needed for the project.

**Comment by parthea** [comment]
I've create a feature request internally. Googlers see b/246948899

**Comment by SakshiSingh25** [comment]
Hello, I'm interested in working on this issue. Kindly guide me with the further process.

**Comment by qua-jones** [comment]
any updates on this request?
