### ISSUE TITLE
File query name filter not working

### ISSUE THREAD

**Issue by StephanMertel** [googleapis/google-api-python-client#2118]
#### Environment details

  - OS type and version: Mac OS Ventura 13.2.1
  - Python version: Python 3.10.10
  - pip version: pip 22.3.1
  - `google-api-python-client` version: 2.70.0

#### Steps to reproduce

  1. Filter csv files by name: `client.files().list(q="mimeType='text/csv' and name contains 'AR_Ab-ops-DO_'", pageSize=1, includeItemsFromAllDrives=True, supportsAllDrives=True).execute()`
  2. Check the retrieved files:
 ```
In [29]: files["files"]
Out[29]:
[{'kind': 'drive#file',
  'driveId': '0***A',
  'mimeType': 'text/csv',
  'id': '1***n',
  'name': 'AR_Ab-ops-U-FI-DO_2022_11.csv',
  'teamDriveId': '0***A'}]
```
Note that the file name `AR_Ab-ops-U-FI-DO_2022_11.csv` does not match the filtered string `'AR_Ab-ops-DO_'`.

**Comment by parthea** [comment]
Hi @StephanMertel,

This appears to be an issue with the API rather than the client library. Please could you try out a similar request in the 'Try this API' interface on [this page](https://developers.google.com/drive/api/v3/reference/files/list) and check whether the issue still exists? This helps to confirm if this is a client library issue or a API issue. If it is an API issue, we'll redirect you to the API support channel so you can get better quality answers. For the Drive API please see https://developers.google.com/drive/api/v3/support.

**Comment by StephanMertel** [comment]
@parthea thanks for your quick response. I can indeed reproduce it with the API interface. Closing this and contacting the drive API support as you suggested. Cheers!

**Comment by StephanMertel** [comment]
For anyone else stumbling over this: I contacted the google drive API support and they told me that when filtering with the query `name contains AR_Ab-ops-DO` both underscores and dashes are treated like spaces, which basically leads to the filter "name contains AR _and_ Ab _and_ ops _and_ DO", but not necessarily in this order.

The only solution they gave me was to retrieve all those files and then do a second filter on my side.
