### ISSUE TITLE
oauth2client needs to be frozen at version 3.0.0 in order to work

### ISSUE THREAD

**Issue by matthewsqor** [googleapis/google-api-python-client#2348]
I was running this library and I got the error
googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0

The solution is simple, we need the requirements file to be complete, specifically have oauth2client frozen at version 3.0.0 in order for discovery_cache to work.

**Comment by parthea** [comment]
Thanks for reporting this issue. As of [version 2.0](https://github.com/googleapis/google-api-python-client?tab=readme-ov-file#version-20-release), public discovery documents are shipped with each release of `google-api-python-client`. In the case of public discovery documents, they no longer need to be downloaded and cached. Please can you clarify if you're fetching discovery artifacts from the internet rather than the ones that are shipped with the library?

See https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md for more information

**Comment by vchudnov-g** [comment]
No response, so closing the issue for now. Please feel free to file a new issue if you have additional questions. Thanks!
