### ISSUE TITLE
Service account with IP restrict

### ISSUE THREAD

**Issue by rueyjye** [googleapis/google-api-python-client#530]
I'm using service account with delegated credentials executing Apps Script API to run a function on Google Apps Script from a Python script via Google's Python client library, and it just works fine.

Then, I am trying to add some IP restriction for it, to make sure it can only execute by the specific IP.

I have tried to add a firewall rule in VPC, which deny all ingress from 0.0.0.0/0 and set the target to the service account. However, running the script after setting the vpc rule is no different than before it.
The firewall rule seems to only target the VM instance used by the service account.

Is there any suggestion for setting IP restriction?

**Comment by mcdonc** [comment]
I think I need some handholding to understand this, apologies.  Background:  I'm helping take care of this repository, but I'm not an expert on every backend API that the client library talks to, nor the configuration capabilities of particular ones, so please be patient.

As far as I can tell from the docs, the Apps Script API is "in the cloud", and there aren't any options to secure by IP restriction for it.  But since you say you added a firewall rule "in VPC", there is clearly something I'm not understanding about the configuration options of the service.  Can you maybe go into a bit more detail, perhaps giving an end-to-end concrete example of what's happening (e.g. I have a hosted script, it does this (show the code)) and then what you want to happen that is different?

**Comment by busunkim96** [comment]
I am closing this since it has been inactive for 6 months, but please let us know if this is still an issue for you @rueyjye.
