### ISSUE TITLE
Empty rows in response from Youtube Analytics API

### ISSUE THREAD

**Issue by alexander-vo** [googleapis/google-api-python-client#573]
Hello!
Need help with youtube analytics api. 
Have this problem:
I want to get some data from youtube analytics. In the developer console I enter the following parameters:
![image](https://user-images.githubusercontent.com/35242752/46405801-12969f80-c712-11e8-9b38-875471dca5ac.png)
with this scopes:
![image](https://user-images.githubusercontent.com/35242752/46405867-51c4f080-c712-11e8-9c24-1f4459a92404.png)
After Oauth2.0 authorization I have the following response from the API:
![image](https://user-images.githubusercontent.com/35242752/46405920-791bbd80-c712-11e8-83f7-4873745b2901.png)
Everything is fine

Now I'm trying to get the same data from my python app using google-api-python-client with service account key.
I have this code:
![image](https://user-images.githubusercontent.com/35242752/46408065-88523980-c719-11e8-9992-0fc11913b198.png)

But after completion, I get the following answer:
![image](https://user-images.githubusercontent.com/35242752/46408038-7a041d80-c719-11e8-8212-91c32fc73f1f.png)

Empty rows. But in fact I need the same result as in the developer console.

I used the following docs to build this:
https://developers.google.com/api-client-library/python/auth/service-accounts
https://developers.google.com/resources/api-libraries/documentation/youtubeAnalytics/v2/python/latest/

Tried to use the same key but with youtube data api v3 - It's OK

What I'm doing wrong? I will be glad to hear your advice

Thank you!

**Comment by tasha5151** [comment]
i've got the same problem, have no idea with it.

**Comment by LindaLawton** [comment]
I didn't realize that YouTube analytics supported service accounts.

mine is reading the service accounts YouTube analytics a count.   Which apears to have no data for that time frame

**Comment by busunkim96** [comment]
As @LindaLawton mentioned, YouTube Analytics are being fetched for the service account. 

When you made queries in the APIs Explorer, all requests were sent on behalf of your user account. In the Python code, you authenticated using the service account credentials that are in `awo182-youtube-key.json`. When you later requested analytics for `ids='CHANNEL==MINE'`, the API returned data for the service account (not your user account). Service accounts belong to an application rather than a specific end user. You can read more about them [here](https://cloud.google.com/iam/docs/understanding-service-accounts). 

It looks like you want to fetch  YouTube Analytics data for your account. In that case, it's probably easiest to use OAuth2.0 credentials. [This python sample](https://github.com/youtube/api-samples/blob/master/python/yt_analytics_report.py) shows how to do that.

Hope this helps!

**Comment by alexander-vo** [comment]
Yeah, you are right. It is not possible to use the service account with Youtube Analytics in this way. I chose a different path with OAuth2.0, I will log in once, and then I will just update the token when I need a server-to-server request. Hope it works.
Thanks for the help! Very useful! We can close this ticket.
