### ISSUE TITLE
Alert Center - List Alerts - 400 Error

### ISSUE THREAD

**Issue by TacticalCheerio** [googleapis/google-api-python-client#764]
#### Environment details

  - OS: Windows 10
  - Python version: 3.7.4
  - pip version: 19.2.3
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce
The following code:
```
from googleapiclient.discovery import build
from google.oauth2 import service_account
SCOPES = ['https://www.googleapis.com/auth/apps.alerts']
CREDENTIALS_FILEPATH = r'path\to\credential\file.json'
credentials = service_account.Credentials.from_service_account_file(CREDENTIALS_FILEPATH, scopes=SCOPES)
alertcli = build('alertcenter', 'v1beta1', credentials=credentials, cache_discovery=False)
response = alertcli.alerts().list().execute()
```
Produces the following error:
```
python .\AlertCenter.py
Traceback (most recent call last):
  File ".\AlertCenter.py", line 20, in <module>
    response = response.execute()
  File "C:\....\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\....\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://alertcenter.googleapis.com/v1beta1/alerts?alt=json returned "Request contains an invalid argument.">
```

The [prerequisites](https://developers.google.com/admin-sdk/alertcenter/guides/prerequisites) have already been checked

**Comment by busunkim96** [comment]
Hi @TacticalCheerio,

There's a fix that should expose the error message, but a release hasn't been cut yet. Can you try installing the library from head?

1. make a new virtualenv `virtualenv env`
2. activate the virtualenv `source env/bin/activate`
3. clone this repo: `git clone https://github.com/googleapis/google-api-python-client.git`
4. install library from source
    ```cd google-api-python-client
    python3 -m pip install .
    ```


You should see a more specific error message below the 400.

**Comment by TacticalCheerio** [comment]
Here's what I got:

```
(env) PS C:\Users\....\AlertCenter> python .\AlertCenter.py
Traceback (most recent call last):
  File ".\AlertCenter.py", line 20, in <module>
    response = response.execute()
  File "C:\Users\....\AlertCenter\DEV\env\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\....\AlertCenter\DEV\env\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://alertcenter.googleapis.com/v1beta1/alerts?alt=json returned "Request contains an invalid argument.">
(env) PS C:\Users\....\AlertCenter> pip list
Package                  Version
------------------------ -------
cachetools               3.1.1
google-api-python-client 1.7.11
google-auth              1.6.3
google-auth-httplib2     0.0.3
httplib2                 0.14.0
oauth2client             4.1.3
pip                      19.3
pyasn1                   0.4.7
pyasn1-modules           0.2.7
rsa                      4.0
setuptools               41.4.0
six                      1.12.0
uritemplate              3.0.0
wheel                    0.33.6
```

**Comment by parthea** [comment]
Hi @TacticalCheerio,

I'm sorry that it took so long to respond to this issue. I ran your example code and I was able to re-produce the issue. I can see that the error message has improved from "Request contains an invalid argument" to "customer id could not be inferred from the request or caller identity." Since the [customerId parameter](https://developers.google.com/admin-sdk/alertcenter/reference/rest/v1beta1/alerts/list) was not provided and the customerId could not be inferred, the error is returned. If you're using domain wide delegation, please try the example code [here](https://developers.google.com/identity/protocols/oauth2/service-account#authorizingrequests) and make sure that you have the `credentials.with_subject()` to impersonate a user account.

I'm going to close off this issue but if you're still having trouble please re-open it with more information.

Googlers see b/144677234
